version: '3.9'
services:
  api:
    build: ./backend
    container_name: fpl_api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: fpl_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: fpl_db
    restart: always
    environment:
      POSTGRES_USER: fpl_user
      POSTGRES_PASSWORD: fpl_pass
      POSTGRES_DB: fpl
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: fpl_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
