version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: fpl-backend
    environment:
      - CMD_MODE=gunicorn
      - ENV=production
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: fpl-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
