#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Backend pre-commit hooks
cd backend
python3 -m pre-commit run --all-files
cd ..

# Frontend pre-commit hooks
cd frontend
pnpm exec vue-tsc --noEmit
pnpm run lint
pnpm run format